### ISSUE TITLE
Bisq Download Link 404 error

### ISSUE THREAD

**Issue by econoalchemist** [bitcoin-intro/bitcoin-intro#3]
Under "Step 12: Buying Privately", the link for the Bisq download is currently set to: `https://github.com/bisq-network/bisq/releases/tag/Download`

This leads to a 404 Page Not Found error.

Consider revising link to: `https://bisq.network/downloads/` 

This was brought to my attention by Twitter user @AxeCapYa

**Comment by 6102bitcoin** [comment]
Thanks. [Merged](https://github.com/bitcoin-intro/bitcoin-intro/commit/8392494a6390d3b14238459130dda886a9aec6c9)
